-- 股票推荐验证系统建表脚本

-- 1. 推荐主表
CREATE TABLE IF NOT EXISTS stock_recommendation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    recommend_date DATE NOT NULL COMMENT '推荐日期',
    code VARCHAR(10) NOT NULL COMMENT '股票代码',
    name VARCHAR(50) COMMENT '股票名称',
    grade VARCHAR(5) NOT NULL COMMENT '评级',
    score INT COMMENT '推荐评分',
    recommend_price DECIMAL(10,3) NOT NULL COMMENT '推荐日收盘价',
    recommend_change DECIMAL(8,2) COMMENT '推荐日涨跌幅',
    is_st TINYINT DEFAULT 0 COMMENT '是否ST股票',
    industry VARCHAR(50) COMMENT '所属行业',
    market_cap DECIMAL(15,2) COMMENT '总市值',
    float_cap DECIMAL(15,2) COMMENT '流通市值',
    support_strong DECIMAL(10,3) COMMENT '强支撑位',
    resistance_strong DECIMAL(10,3) COMMENT '强压力位',
    ma20 DECIMAL(10,3) COMMENT '20日均线',
    ma60 DECIMAL(10,3) COMMENT '60日均线',
    cvd_signal VARCHAR(20) COMMENT 'CVD信号',
    reasons TEXT COMMENT '推荐理由',
    stop_loss_price DECIMAL(10,3) COMMENT '止损价',
    take_profit_price DECIMAL(10,3) COMMENT '止盈价',
    stop_loss_pct DECIMAL(5,2) DEFAULT -5.00 COMMENT '止损线',
    take_profit_pct DECIMAL(5,2) DEFAULT 10.00 COMMENT '止盈线',
    max_profit DECIMAL(8,2) DEFAULT 0 COMMENT '最大收益',
    max_loss DECIMAL(8,2) DEFAULT 0 COMMENT '最大亏损',
    final_profit DECIMAL(8,2) DEFAULT 0 COMMENT '最终收益',
    best_day INT DEFAULT 0 COMMENT '最佳收益日期',
    worst_day INT DEFAULT 0 COMMENT '最差收益日期',
    status VARCHAR(20) DEFAULT 'tracking' COMMENT '状态',
    stop_reason VARCHAR(50) COMMENT '终止原因',
    stopped_at DATE COMMENT '终止日期',
    user_buy_date DATE COMMENT '用户实际买入日期',
    user_sell_date DATE COMMENT '用户实际卖出日期',
    user_notes TEXT COMMENT '用户备注',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_recommend (recommend_date, code),
    INDEX idx_date (recommend_date),
    INDEX idx_code (code),
    INDEX idx_grade (grade),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票推荐主表';

-- 2. 跟踪明细表
CREATE TABLE IF NOT EXISTS stock_pick_tracking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    recommend_id BIGINT NOT NULL COMMENT '推荐记录ID',
    recommend_date DATE NOT NULL COMMENT '推荐日期',
    code VARCHAR(10) NOT NULL COMMENT '股票代码',
    track_day INT NOT NULL COMMENT '跟踪天数',
    track_date DATE NOT NULL COMMENT '跟踪日期',
    open_price DECIMAL(10,3) COMMENT '开盘价',
    high_price DECIMAL(10,3) COMMENT '最高价',
    low_price DECIMAL(10,3) COMMENT '最低价',
    close_price DECIMAL(10,3) NOT NULL COMMENT '收盘价',
    prev_close_price DECIMAL(10,3) COMMENT '前一日收盘价',
    daily_change DECIMAL(8,2) COMMENT '当日涨跌幅',
    cumulative_profit DECIMAL(8,2) NOT NULL COMMENT '累计收益',
    volume BIGINT COMMENT '成交量',
    amount DECIMAL(15,2) COMMENT '成交额',
    turnover_rate DECIMAL(8,2) COMMENT '换手率',
    signal_type VARCHAR(20) COMMENT '信号类型',
    signal_reason VARCHAR(100) COMMENT '信号原因',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_track (recommend_id, track_day),
    INDEX idx_recommend_date (recommend_date),
    INDEX idx_code (code),
    INDEX idx_track_date (track_date),
    INDEX idx_cumulative_profit (cumulative_profit),
    CONSTRAINT fk_recommend_id FOREIGN KEY (recommend_id) REFERENCES stock_recommendation(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票推荐跟踪明细表';
